### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by moshe-kabala**

### CODE REVIEW

**Review by YuvalFeldman — COMMENTED** [review]
Why do we have 166 docs files?

**Comment by YuvalFeldman** [comment]
How where there not that many docs last time we ran it? Did we not run it at all since adding code? also it looks like a ton of the docs are related to kubectl which seems unrelated to our code..

**Review by yotamazriel — APPROVED** [review]
LGTM

**Comment by yotamazriel** [comment]
> > How where there not that many docs last time we ran it? Did we not run it at all since adding code? also it looks like a ton of the docs are related to kubectl which seems unrelated to our code..
> 
> I think we just didn't ran it since we added the kubectl to the tools and now it added the kubectl help docs

And also it will allow us to use auto complete

**Comment by yotamazriel** [comment]
@YuvalFeldman Let us know if you have any other concerns other wise we'll merge it

**Comment by moshe-kabala** [comment]
@YuvalFeldman  Currently, we have added `k3s` and `kubectl` commands to our CLI, maybe we will reconsider it and then remove the docs as well

**Comment by yotamazriel** [comment]
> @YuvalFeldman Currently, we have added `k3s` and `kubectl` commands to our CLI, maybe we will reconsider it and then remove the docs as well

Let's keep it for now

**Comment by YuvalFeldman** [comment]
As mentioned i dont think this should be included in our docs. Its not related to our provided functionality and feels like we just auto generated docs for an entire 3d part library we're using in our code, Other than that you got approval so merge if you disagree with me. There isnt anything here that will break the code, it just looks bad IMHO 🤷

**Pull request merged**
